[settings]
python.uv_venv_auto = true

[tools]
black = "26.3.0"
python = "3.14.3"
uv = "0.10.9"

[tasks.start]
description = "Start the program"
run = "uv run src/main.py"

[tasks.format]
run = "black src"

[tasks.lint]
run = "pylint src"

[env]
SERVER_URL="http://localhost:5173"
