[settings]
python.uv_venv_auto = true

[tools]
black = "latest"
python = "3.14.0"
uv = "0.9.5"

[tasks.start]
description = "Start the program"
run = "uv run main.py"

[env]
SERVER_URL="http://localhost:5173"
